name: Test multi-artifact upload

on:
  push:
  workflow_dispatch:

jobs:
  test-multi-artifact-upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup test files
        run: |
          mkdir ./test-data
          curl -o ./test-data/baa.jpg https://www.w3.org/MarkUp/Test/xhtml-print/20050519/tests/jpeg420exif.jpg
          curl -o ./test-data/foo.png https://upload.wikimedia.org/wikipedia/commons/8/85/Logo-Test.png
          mkdir ./test-data/nested
          echo "My name is Shaun" > ./test-data/nested/sheep.txt

      - uses: ./
        id: upload-multiple-artifacts
        with:
          files-to-upload: '["./test-data/baa.jpg", "./test-data/foo.png", "./test-data/nested/sheep.txt"]'

      - name: Check output
        run: |
          ACTUAL=$(echo '${{ steps.upload-multiple-artifacts.outputs.artifact-ids }}' | jq -S '[ keys[] ]')
          EXPECTED=$(echo '["./test-data/baa.jpg", "./test-data/foo.png", "./test-data/nested/sheep.txt"]' | jq -S .)
          echo "Expect: $EXPECTED"
          echo "Actual: $ACTUAL"
          if [ "$ACTUAL" != "$EXPECTED" ]; then
            echo "Assertion error"
            exit 1;
          fi

      - name: Ensure files were renamed back correctly
        run: |
          ls ./test-data
          NUM_FILES=$(ls ./test-data | wc -l)
          if [[ "$NUM_FILES" -ne 3 ]]; then
            echo "Assertion error"
            exit 1;
          fi
